name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d%H%M%S')"
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'tevents-${{ steps.date.outputs.date }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig .github install.cmd README.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "tevents-${{ steps.date.outputs.date }}.zip"
        tag: ${{ steps.date.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}
